name: "Releases"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Make pre-release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Check status"
        run: |
          mv branch/master/latest/UNWDS.phar branch/master/latest/UNWDS_latest-master.phar
          mv branch/stable/latest/UNWDS.phar branch/stable/latest/UNWDS_latest-stable.phar
          echo "OK. Release now!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GHTOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Released from UNWDS CI"
          files: |
            branch/master/latest/UNWDS_latest-master.phar
            branch/stable/latest/UNWDS_latest-stable.phar
